export const aiTokenStreamSequence: string[] = [
  '{',
  '  "basics": {',
  '    "name": "Akinyemi Olamilekan",',
  '    "label": "Senior Software Engineer",',
  '    "email": "temi@example.com",',
  '    "phone": "+234 800 555 0119",',
  '    "profiles": [',
  '      { "network": "GitHub", "url": "github.com/…" },',
  '      { "network": "LinkedIn", "url": "linkedin.com/…" }',
  '    ]',
  '  },',
  '  "work": [',
  '    {',
  '      "position": "Senior Software Engineer",',
  '      "name": "Acme Corp",',
  '      "startDate": "2023-01",',
  '      "endDate": "Present",',
  '      "highlights": [',
  '        "Led data-pipeline rewrite…",',
  '        "Mentored 4 engineers…"',
  '      ]',
  '    }',
  '  ],',
  '  "education": [',
  '    {',
  '      "institution": "University of …",',
  '      "studyType": "B.Sc.",',
  '      "area": "Computer Science"',
  '    }',
  '  ],',
  '  "skills": [',
  '    { "name": "Programming Languages",',
  '      "keywords": ["TypeScript", "Python", "Go"] }',
  '  ]',
  '}',
];
