import type { IResumeVariantStyle } from '@/interfaces/i-resume-variant-style';
import type { ResumeVariant } from '@/types/resume-variant-type';

export const resumeVariantStyles: Record<ResumeVariant, IResumeVariantStyle> = {
  'modern-minimal': {
    paper: 'p-10 text-[calc(10.5pt*var(--resume-type-scale,1))] leading-[var(--resume-line-height,1.45)]',
    name: 'font-display text-[calc(22pt*var(--resume-type-scale,1))] font-semibold tracking-[-0.02em] text-resume-ink',
    label: 'mt-1 font-sans text-[calc(10pt*var(--resume-type-scale,1))] font-normal tracking-[0] text-resume-muted',
    contact: 'mt-3 font-sans text-[calc(8.5pt*var(--resume-type-scale,1))] text-resume-muted',
    sectionHeading:
      'mt-7 mb-2 font-display text-[calc(8.5pt*var(--resume-type-scale,1))] font-semibold uppercase tracking-[0.16em] text-resume-ink',
    summary: 'font-sans text-resume-ink leading-[var(--resume-line-height,1.5)]',
    entryHeader: 'mt-3 flex items-baseline justify-between gap-3',
    entryRole: 'font-display text-[calc(10.5pt*var(--resume-type-scale,1))] font-semibold text-resume-ink',
    entryCompany: 'font-sans text-[calc(9.5pt*var(--resume-type-scale,1))] text-resume-muted',
    entryDates: 'font-sans text-[calc(8.5pt*var(--resume-type-scale,1))] text-resume-muted tabular-nums',
    bullet: 'mt-1 font-sans text-resume-ink leading-[var(--resume-line-height,1.5)]',
    skillsGroupLabel: 'font-sans text-[calc(9.5pt*var(--resume-type-scale,1))] font-semibold text-resume-ink',
    skillsList: 'font-sans text-resume-ink',
    rule: null,
  },
  'classic-serif': {
    paper: 'p-10 text-[calc(10.5pt*var(--resume-type-scale,1))] leading-[var(--resume-line-height,1.4)]',
    name: 'font-display text-[calc(24pt*var(--resume-type-scale,1))] font-medium tracking-[-0.01em] text-resume-ink text-center',
    label: 'mt-0.5 font-sans italic text-[calc(10pt*var(--resume-type-scale,1))] text-resume-muted text-center',
    contact: 'mt-2 font-sans text-[calc(8.5pt*var(--resume-type-scale,1))] text-resume-muted text-center',
    sectionHeading:
      'mt-7 mb-2 font-display text-[calc(10pt*var(--resume-type-scale,1))] font-semibold uppercase tracking-[0.22em] text-resume-ink border-b border-resume-rule pb-1',
    summary: 'font-sans text-resume-ink leading-[var(--resume-line-height,1.55)]',
    entryHeader: 'mt-3 flex items-baseline justify-between gap-3',
    entryRole: 'font-display text-[calc(10.5pt*var(--resume-type-scale,1))] font-semibold text-resume-ink',
    entryCompany: 'font-sans italic text-[calc(10pt*var(--resume-type-scale,1))] text-resume-muted',
    entryDates: 'font-sans text-[calc(9pt*var(--resume-type-scale,1))] text-resume-muted tabular-nums',
    bullet: 'mt-1 font-sans text-resume-ink leading-[var(--resume-line-height,1.5)]',
    skillsGroupLabel: 'font-sans italic text-[calc(10pt*var(--resume-type-scale,1))] text-resume-ink',
    skillsList: 'font-sans text-resume-ink',
    rule: 'mx-auto my-1 h-px w-12 bg-resume-rule',
  },
  'tech-sans': {
    paper: 'p-10 text-[calc(10.5pt*var(--resume-type-scale,1))] leading-[var(--resume-line-height,1.45)]',
    name: 'font-display text-[calc(22pt*var(--resume-type-scale,1))] font-semibold tracking-[-0.025em] text-resume-ink',
    label: 'mt-0.5 font-sans text-[calc(10.5pt*var(--resume-type-scale,1))] font-normal tracking-[0] text-accent-ink',
    contact: 'mt-3 font-mono text-[calc(8.5pt*var(--resume-type-scale,1))] text-resume-muted tabular-nums',
    sectionHeading:
      'mt-7 mb-2 font-display text-[calc(9.5pt*var(--resume-type-scale,1))] font-semibold text-resume-ink border-b border-accent pb-1',
    summary: 'font-sans text-resume-ink leading-[var(--resume-line-height,1.5)]',
    entryHeader: 'mt-3 flex items-baseline justify-between gap-3',
    entryRole: 'font-display text-[calc(10.5pt*var(--resume-type-scale,1))] font-semibold text-resume-ink',
    entryCompany: 'font-sans text-[calc(9.5pt*var(--resume-type-scale,1))] text-resume-muted',
    entryDates: 'font-mono text-[calc(8.5pt*var(--resume-type-scale,1))] text-resume-muted tabular-nums',
    bullet: 'mt-1 font-sans text-resume-ink leading-[var(--resume-line-height,1.5)]',
    skillsGroupLabel: 'font-sans text-[calc(9.5pt*var(--resume-type-scale,1))] font-semibold text-resume-ink',
    skillsList: 'font-mono text-[calc(9.5pt*var(--resume-type-scale,1))] text-resume-ink',
    rule: null,
  },
  executive: {
    paper: 'p-10 text-[calc(10.5pt*var(--resume-type-scale,1))] leading-[var(--resume-line-height,1.35)]',
    name: 'font-display text-[calc(28pt*var(--resume-type-scale,1))] font-semibold tracking-[-0.025em] text-resume-ink',
    label: 'mt-0.5 font-sans text-[calc(11pt*var(--resume-type-scale,1))] font-normal tracking-[0] text-resume-muted',
    contact: 'mt-2 font-sans text-[calc(8.5pt*var(--resume-type-scale,1))] text-resume-muted',
    sectionHeading:
      'mt-6 mb-1.5 font-display text-[calc(10pt*var(--resume-type-scale,1))] font-semibold uppercase tracking-[0.18em] text-resume-ink border-b-2 border-resume-ink pb-1',
    summary: 'font-sans text-resume-ink leading-[var(--resume-line-height,1.5)]',
    entryHeader: 'mt-2.5 flex items-baseline justify-between gap-3',
    entryRole: 'font-display text-[calc(11pt*var(--resume-type-scale,1))] font-semibold text-resume-ink',
    entryCompany: 'font-sans text-[calc(10pt*var(--resume-type-scale,1))] text-resume-muted',
    entryDates: 'font-sans text-[calc(8.5pt*var(--resume-type-scale,1))] text-resume-muted tabular-nums',
    bullet: 'mt-1 font-sans text-resume-ink leading-[var(--resume-line-height,1.45)]',
    skillsGroupLabel: 'font-sans text-[calc(9.5pt*var(--resume-type-scale,1))] font-semibold text-resume-ink',
    skillsList: 'font-sans text-resume-ink',
    rule: null,
  },
  compact: {
    paper: 'p-8 text-[calc(10pt*var(--resume-type-scale,1))] leading-[var(--resume-line-height,1.35)]',
    name: 'font-display text-[calc(20pt*var(--resume-type-scale,1))] font-semibold tracking-[-0.02em] text-resume-ink',
    label: 'mt-0.5 font-sans text-[calc(9.5pt*var(--resume-type-scale,1))] font-normal text-resume-muted',
    contact: 'mt-2 font-sans text-[calc(8pt*var(--resume-type-scale,1))] text-resume-muted',
    sectionHeading:
      'mt-5 mb-1.5 font-display text-[calc(8.5pt*var(--resume-type-scale,1))] font-semibold uppercase tracking-[0.16em] text-resume-ink',
    summary: 'font-sans text-[calc(9.5pt*var(--resume-type-scale,1))] text-resume-ink leading-[var(--resume-line-height,1.45)]',
    entryHeader: 'mt-2 flex items-baseline justify-between gap-3',
    entryRole: 'font-display text-[calc(10pt*var(--resume-type-scale,1))] font-semibold text-resume-ink',
    entryCompany: 'font-sans text-[calc(9pt*var(--resume-type-scale,1))] text-resume-muted',
    entryDates: 'font-sans text-[calc(8pt*var(--resume-type-scale,1))] text-resume-muted tabular-nums',
    bullet: 'mt-0.5 font-sans text-[calc(9.5pt*var(--resume-type-scale,1))] text-resume-ink leading-[var(--resume-line-height,1.4)]',
    skillsGroupLabel: 'font-sans text-[calc(9pt*var(--resume-type-scale,1))] font-semibold text-resume-ink',
    skillsList: 'font-sans text-[calc(9.5pt*var(--resume-type-scale,1))] text-resume-ink',
    rule: null,
  },
  editorial: {
    paper: 'p-10 text-[calc(10.5pt*var(--resume-type-scale,1))] leading-[var(--resume-line-height,1.5)]',
    name: 'font-display text-[calc(30pt*var(--resume-type-scale,1))] font-semibold tracking-[-0.03em] leading-[var(--resume-line-height,0.92)] text-resume-ink',
    label: 'mt-2 font-sans italic text-[calc(11pt*var(--resume-type-scale,1))] text-resume-muted',
    contact: 'mt-3 font-sans text-[calc(8.5pt*var(--resume-type-scale,1))] text-resume-muted',
    sectionHeading:
      'mt-7 mb-2 font-display text-[calc(12pt*var(--resume-type-scale,1))] font-semibold text-resume-ink pl-3 border-l-2 border-accent',
    summary: 'font-sans text-resume-ink leading-[var(--resume-line-height,1.55)]',
    entryHeader: 'mt-3 flex items-baseline justify-between gap-3',
    entryRole: 'font-display text-[calc(11pt*var(--resume-type-scale,1))] font-semibold text-resume-ink',
    entryCompany: 'font-sans italic text-[calc(10pt*var(--resume-type-scale,1))] text-resume-muted',
    entryDates: 'font-sans text-[calc(8.5pt*var(--resume-type-scale,1))] text-resume-muted tabular-nums',
    bullet: 'mt-1 font-sans text-resume-ink leading-[var(--resume-line-height,1.55)]',
    skillsGroupLabel: 'font-sans text-[calc(10pt*var(--resume-type-scale,1))] font-semibold text-resume-ink',
    skillsList: 'font-sans text-resume-ink',
    rule: null,
  },
};
