import type { IResumeVariantStyle } from '@/interfaces/i-resume-variant-style';
import type { ResumeVariant } from '@/types/resume-variant-type';

export const resumeVariantStyles: Record<ResumeVariant, IResumeVariantStyle> = {
  'modern-minimal': {
    paper: 'p-10 text-[10.5pt] leading-[1.45]',
    name: 'font-display text-[22pt] font-semibold tracking-[-0.02em] text-resume-ink',
    label: 'mt-1 font-sans text-[10pt] font-normal tracking-[0] text-resume-muted',
    contact: 'mt-3 font-sans text-[8.5pt] text-resume-muted',
    sectionHeading:
      'mt-7 mb-2 font-display text-[8.5pt] font-semibold uppercase tracking-[0.16em] text-resume-ink',
    summary: 'font-sans text-resume-ink leading-[1.5]',
    entryHeader: 'mt-3 flex items-baseline justify-between gap-3',
    entryRole: 'font-display text-[10.5pt] font-semibold text-resume-ink',
    entryCompany: 'font-sans text-[9.5pt] text-resume-muted',
    entryDates: 'font-sans text-[8.5pt] text-resume-muted tabular-nums',
    bullet: 'mt-1 font-sans text-resume-ink leading-[1.5]',
    skillsGroupLabel: 'font-sans text-[9.5pt] font-semibold text-resume-ink',
    skillsList: 'font-sans text-resume-ink',
    rule: null,
  },
  'classic-serif': {
    paper: 'p-10 text-[10.5pt] leading-[1.4]',
    name: 'font-display text-[24pt] font-medium tracking-[-0.01em] text-resume-ink text-center',
    label: 'mt-0.5 font-sans italic text-[10pt] text-resume-muted text-center',
    contact: 'mt-2 font-sans text-[8.5pt] text-resume-muted text-center',
    sectionHeading:
      'mt-7 mb-2 font-display text-[10pt] font-semibold uppercase tracking-[0.22em] text-resume-ink border-b border-resume-rule pb-1',
    summary: 'font-sans text-resume-ink leading-[1.55]',
    entryHeader: 'mt-3 flex items-baseline justify-between gap-3',
    entryRole: 'font-display text-[10.5pt] font-semibold text-resume-ink',
    entryCompany: 'font-sans italic text-[10pt] text-resume-muted',
    entryDates: 'font-sans text-[9pt] text-resume-muted tabular-nums',
    bullet: 'mt-1 font-sans text-resume-ink leading-[1.5]',
    skillsGroupLabel: 'font-sans italic text-[10pt] text-resume-ink',
    skillsList: 'font-sans text-resume-ink',
    rule: 'mx-auto my-1 h-px w-12 bg-resume-rule',
  },
  'tech-sans': {
    paper: 'p-10 text-[10.5pt] leading-[1.45]',
    name: 'font-display text-[22pt] font-semibold tracking-[-0.025em] text-resume-ink',
    label: 'mt-0.5 font-sans text-[10.5pt] font-normal tracking-[0] text-accent-ink',
    contact: 'mt-3 font-mono text-[8.5pt] text-resume-muted tabular-nums',
    sectionHeading:
      'mt-7 mb-2 font-display text-[9.5pt] font-semibold text-resume-ink border-b border-accent pb-1',
    summary: 'font-sans text-resume-ink leading-[1.5]',
    entryHeader: 'mt-3 flex items-baseline justify-between gap-3',
    entryRole: 'font-display text-[10.5pt] font-semibold text-resume-ink',
    entryCompany: 'font-sans text-[9.5pt] text-resume-muted',
    entryDates: 'font-mono text-[8.5pt] text-resume-muted tabular-nums',
    bullet: 'mt-1 font-sans text-resume-ink leading-[1.5]',
    skillsGroupLabel: 'font-sans text-[9.5pt] font-semibold text-resume-ink',
    skillsList: 'font-mono text-[9.5pt] text-resume-ink',
    rule: null,
  },
  executive: {
    paper: 'p-10 text-[10.5pt] leading-[1.35]',
    name: 'font-display text-[28pt] font-semibold tracking-[-0.025em] text-resume-ink',
    label: 'mt-0.5 font-sans text-[11pt] font-normal tracking-[0] text-resume-muted',
    contact: 'mt-2 font-sans text-[8.5pt] text-resume-muted',
    sectionHeading:
      'mt-6 mb-1.5 font-display text-[10pt] font-semibold uppercase tracking-[0.18em] text-resume-ink border-b-2 border-resume-ink pb-1',
    summary: 'font-sans text-resume-ink leading-[1.5]',
    entryHeader: 'mt-2.5 flex items-baseline justify-between gap-3',
    entryRole: 'font-display text-[11pt] font-semibold text-resume-ink',
    entryCompany: 'font-sans text-[10pt] text-resume-muted',
    entryDates: 'font-sans text-[8.5pt] text-resume-muted tabular-nums',
    bullet: 'mt-1 font-sans text-resume-ink leading-[1.45]',
    skillsGroupLabel: 'font-sans text-[9.5pt] font-semibold text-resume-ink',
    skillsList: 'font-sans text-resume-ink',
    rule: null,
  },
  compact: {
    paper: 'p-8 text-[10pt] leading-[1.35]',
    name: 'font-display text-[20pt] font-semibold tracking-[-0.02em] text-resume-ink',
    label: 'mt-0.5 font-sans text-[9.5pt] font-normal text-resume-muted',
    contact: 'mt-2 font-sans text-[8pt] text-resume-muted',
    sectionHeading:
      'mt-5 mb-1.5 font-display text-[8.5pt] font-semibold uppercase tracking-[0.16em] text-resume-ink',
    summary: 'font-sans text-[9.5pt] text-resume-ink leading-[1.45]',
    entryHeader: 'mt-2 flex items-baseline justify-between gap-3',
    entryRole: 'font-display text-[10pt] font-semibold text-resume-ink',
    entryCompany: 'font-sans text-[9pt] text-resume-muted',
    entryDates: 'font-sans text-[8pt] text-resume-muted tabular-nums',
    bullet: 'mt-0.5 font-sans text-[9.5pt] text-resume-ink leading-[1.4]',
    skillsGroupLabel: 'font-sans text-[9pt] font-semibold text-resume-ink',
    skillsList: 'font-sans text-[9.5pt] text-resume-ink',
    rule: null,
  },
  editorial: {
    paper: 'p-10 text-[10.5pt] leading-[1.5]',
    name: 'font-display text-[30pt] font-semibold tracking-[-0.03em] leading-[0.92] text-resume-ink',
    label: 'mt-2 font-sans italic text-[11pt] text-resume-muted',
    contact: 'mt-3 font-sans text-[8.5pt] text-resume-muted',
    sectionHeading:
      'mt-7 mb-2 font-display text-[12pt] font-semibold text-resume-ink pl-3 border-l-2 border-accent',
    summary: 'font-sans text-resume-ink leading-[1.55]',
    entryHeader: 'mt-3 flex items-baseline justify-between gap-3',
    entryRole: 'font-display text-[11pt] font-semibold text-resume-ink',
    entryCompany: 'font-sans italic text-[10pt] text-resume-muted',
    entryDates: 'font-sans text-[8.5pt] text-resume-muted tabular-nums',
    bullet: 'mt-1 font-sans text-resume-ink leading-[1.55]',
    skillsGroupLabel: 'font-sans text-[10pt] font-semibold text-resume-ink',
    skillsList: 'font-sans text-resume-ink',
    rule: null,
  },
};
