import type { ISkillEntry } from '@/interfaces/i-skill-entry';

export const skillTaxonomy: ISkillEntry[] = [
  { name: 'JavaScript', aliases: ['js'], category: 'programming-languages', kind: 'language' },
  { name: 'TypeScript', aliases: ['ts'], category: 'programming-languages', kind: 'language' },
  { name: 'Python', category: 'programming-languages', kind: 'language' },
  { name: 'Java', category: 'programming-languages', kind: 'language' },
  { name: 'Go', aliases: ['golang'], category: 'programming-languages', kind: 'language' },
  { name: 'Rust', category: 'programming-languages', kind: 'language' },
  { name: 'C++', aliases: ['cpp', 'cplusplus'], category: 'programming-languages', kind: 'language' },
  { name: 'C#', aliases: ['csharp'], category: 'programming-languages', kind: 'language' },
  { name: 'C', category: 'programming-languages', kind: 'language' },
  { name: 'Ruby', category: 'programming-languages', kind: 'language' },
  { name: 'PHP', category: 'programming-languages', kind: 'language' },
  { name: 'Scala', category: 'programming-languages', kind: 'language' },
  { name: 'Kotlin', category: 'programming-languages', kind: 'language' },
  { name: 'Swift', category: 'programming-languages', kind: 'language' },
  { name: 'Objective-C', aliases: ['objc'], category: 'programming-languages', kind: 'language' },
  { name: 'Dart', category: 'programming-languages', kind: 'language' },
  { name: 'Elixir', category: 'programming-languages', kind: 'language' },
  { name: 'Erlang', category: 'programming-languages', kind: 'language' },
  { name: 'Haskell', category: 'programming-languages', kind: 'language' },
  { name: 'Clojure', category: 'programming-languages', kind: 'language' },
  { name: 'F#', aliases: ['fsharp'], category: 'programming-languages', kind: 'language' },
  { name: 'OCaml', category: 'programming-languages', kind: 'language' },
  { name: 'Lua', category: 'programming-languages', kind: 'language' },
  { name: 'R', category: 'programming-languages', kind: 'language' },
  { name: 'MATLAB', category: 'programming-languages', kind: 'language' },
  { name: 'Julia', category: 'programming-languages', kind: 'language' },
  { name: 'Perl', category: 'programming-languages', kind: 'language' },
  { name: 'Bash', aliases: ['shell scripting'], category: 'programming-languages', kind: 'language' },
  { name: 'PowerShell', category: 'programming-languages', kind: 'language' },
  { name: 'SQL', category: 'programming-languages', kind: 'language' },
  { name: 'GraphQL', category: 'programming-languages', kind: 'language' },
  { name: 'Solidity', category: 'programming-languages', kind: 'language' },
  { name: 'Assembly', category: 'programming-languages', kind: 'language' },
  { name: 'COBOL', category: 'programming-languages', kind: 'language' },
  { name: 'VBA', category: 'programming-languages', kind: 'language' },

  { name: 'HTML', aliases: ['html5'], category: 'web-frontend', kind: 'language' },
  { name: 'CSS', aliases: ['css3'], category: 'web-frontend', kind: 'language' },
  { name: 'React', aliases: ['react.js', 'reactjs'], category: 'web-frontend', kind: 'framework' },
  { name: 'Vue', aliases: ['vue.js', 'vuejs', 'vue 3'], category: 'web-frontend', kind: 'framework' },
  { name: 'Angular', aliases: ['angular.js', 'angularjs'], category: 'web-frontend', kind: 'framework' },
  { name: 'Svelte', aliases: ['sveltekit'], category: 'web-frontend', kind: 'framework' },
  { name: 'Next.js', aliases: ['nextjs', 'next'], category: 'web-frontend', kind: 'framework' },
  { name: 'Nuxt', aliases: ['nuxt.js', 'nuxtjs'], category: 'web-frontend', kind: 'framework' },
  { name: 'Remix', category: 'web-frontend', kind: 'framework' },
  { name: 'Gatsby', category: 'web-frontend', kind: 'framework' },
  { name: 'Astro', category: 'web-frontend', kind: 'framework' },
  { name: 'SolidJS', aliases: ['solid'], category: 'web-frontend', kind: 'framework' },
  { name: 'Qwik', category: 'web-frontend', kind: 'framework' },
  { name: 'Tailwind CSS', aliases: ['tailwind', 'tailwindcss'], category: 'web-frontend', kind: 'framework' },
  { name: 'Bootstrap', category: 'web-frontend', kind: 'framework' },
  { name: 'Material UI', aliases: ['mui', 'material-ui'], category: 'web-frontend', kind: 'library' },
  { name: 'Chakra UI', aliases: ['chakra'], category: 'web-frontend', kind: 'library' },
  { name: 'shadcn/ui', aliases: ['shadcn'], category: 'web-frontend', kind: 'library' },
  { name: 'Sass', aliases: ['scss'], category: 'web-frontend', kind: 'tool' },
  { name: 'Less', category: 'web-frontend', kind: 'tool' },
  { name: 'Webpack', category: 'web-frontend', kind: 'tool' },
  { name: 'Vite', category: 'web-frontend', kind: 'tool' },
  { name: 'Rollup', aliases: ['rolldown'], category: 'web-frontend', kind: 'tool' },
  { name: 'Parcel', category: 'web-frontend', kind: 'tool' },
  { name: 'esbuild', category: 'web-frontend', kind: 'tool' },
  { name: 'Babel', category: 'web-frontend', kind: 'tool' },
  { name: 'Turbopack', category: 'web-frontend', kind: 'tool' },
  { name: 'Redux', aliases: ['redux toolkit', 'rtk'], category: 'web-frontend', kind: 'library' },
  { name: 'Zustand', category: 'web-frontend', kind: 'library' },
  { name: 'Jotai', category: 'web-frontend', kind: 'library' },
  { name: 'MobX', category: 'web-frontend', kind: 'library' },
  { name: 'RxJS', category: 'web-frontend', kind: 'library' },
  { name: 'TanStack Query', aliases: ['react query'], category: 'web-frontend', kind: 'library' },
  { name: 'TanStack Router', category: 'web-frontend', kind: 'library' },
  { name: 'React Router', category: 'web-frontend', kind: 'library' },
  { name: 'jQuery', category: 'web-frontend', kind: 'library' },
  { name: 'Apollo Client', aliases: ['apollo'], category: 'web-frontend', kind: 'library' },
  { name: 'Storybook', category: 'web-frontend', kind: 'tool' },
  { name: 'WebSockets', aliases: ['websocket', 'ws'], category: 'web-frontend', kind: 'concept' },
  { name: 'Server-Sent Events', aliases: ['sse'], category: 'web-frontend', kind: 'concept' },
  { name: 'Progressive Web Apps', aliases: ['pwa'], category: 'web-frontend', kind: 'concept' },
  { name: 'Service Workers', category: 'web-frontend', kind: 'concept' },
  { name: 'WebAssembly', aliases: ['wasm'], category: 'web-frontend', kind: 'concept' },
  { name: 'Server-Side Rendering', aliases: ['ssr'], category: 'web-frontend', kind: 'concept' },
  { name: 'Static Site Generation', aliases: ['ssg'], category: 'web-frontend', kind: 'concept' },
  { name: 'Incremental Static Regeneration', aliases: ['isr'], category: 'web-frontend', kind: 'concept' },
  { name: 'Accessibility', aliases: ['a11y', 'aria', 'wcag'], category: 'web-frontend', kind: 'concept' },
  { name: 'Web Vitals', aliases: ['core web vitals'], category: 'web-frontend', kind: 'concept' },
  { name: 'Responsive Design', category: 'web-frontend', kind: 'concept' },
  { name: 'Micro-frontends', category: 'web-frontend', kind: 'concept' },
  { name: 'Web Components', category: 'web-frontend', kind: 'concept' },

  { name: 'Node.js', aliases: ['nodejs', 'node'], category: 'web-backend', kind: 'platform' },
  { name: 'Express', aliases: ['express.js', 'expressjs'], category: 'web-backend', kind: 'framework' },
  { name: 'Koa', aliases: ['koa.js'], category: 'web-backend', kind: 'framework' },
  { name: 'NestJS', aliases: ['nest.js'], category: 'web-backend', kind: 'framework' },
  { name: 'Fastify', category: 'web-backend', kind: 'framework' },
  { name: 'Hono', category: 'web-backend', kind: 'framework' },
  { name: 'Bun', category: 'web-backend', kind: 'platform' },
  { name: 'Deno', category: 'web-backend', kind: 'platform' },
  { name: 'Django', category: 'web-backend', kind: 'framework' },
  { name: 'Flask', category: 'web-backend', kind: 'framework' },
  { name: 'FastAPI', category: 'web-backend', kind: 'framework' },
  { name: 'Pyramid', category: 'web-backend', kind: 'framework' },
  { name: 'Tornado', category: 'web-backend', kind: 'framework' },
  { name: 'Ruby on Rails', aliases: ['rails', 'ror'], category: 'web-backend', kind: 'framework' },
  { name: 'Sinatra', category: 'web-backend', kind: 'framework' },
  { name: 'Phoenix', category: 'web-backend', kind: 'framework' },
  { name: 'Spring Boot', category: 'web-backend', kind: 'framework' },
  { name: 'Spring', aliases: ['spring framework'], category: 'web-backend', kind: 'framework' },
  { name: 'Micronaut', category: 'web-backend', kind: 'framework' },
  { name: 'Quarkus', category: 'web-backend', kind: 'framework' },
  { name: '.NET', aliases: ['dotnet', '.net core'], category: 'web-backend', kind: 'platform' },
  { name: 'ASP.NET', aliases: ['asp.net core'], category: 'web-backend', kind: 'framework' },
  { name: 'Laravel', category: 'web-backend', kind: 'framework' },
  { name: 'Symfony', category: 'web-backend', kind: 'framework' },
  { name: 'CodeIgniter', category: 'web-backend', kind: 'framework' },
  { name: 'Gin', category: 'web-backend', kind: 'framework' },
  { name: 'Echo', category: 'web-backend', kind: 'framework' },
  { name: 'Fiber', category: 'web-backend', kind: 'framework' },
  { name: 'Actix', category: 'web-backend', kind: 'framework' },
  { name: 'Axum', category: 'web-backend', kind: 'framework' },
  { name: 'Rocket', category: 'web-backend', kind: 'framework' },
  { name: 'REST', aliases: ['restful', 'rest api'], category: 'web-backend', kind: 'concept' },
  { name: 'gRPC', category: 'web-backend', kind: 'concept' },
  { name: 'tRPC', category: 'web-backend', kind: 'concept' },
  { name: 'OpenAPI', aliases: ['swagger'], category: 'web-backend', kind: 'concept' },
  { name: 'JWT', aliases: ['json web token'], category: 'web-backend', kind: 'concept' },
  { name: 'OAuth', aliases: ['oauth2', 'oauth 2.0'], category: 'web-backend', kind: 'concept' },
  { name: 'OIDC', aliases: ['openid connect'], category: 'web-backend', kind: 'concept' },
  { name: 'SAML', category: 'web-backend', kind: 'concept' },
  { name: 'Microservices', aliases: ['microservice architecture'], category: 'web-backend', kind: 'concept' },
  { name: 'Event-Driven Architecture', aliases: ['eda'], category: 'web-backend', kind: 'concept' },
  { name: 'Domain-Driven Design', aliases: ['ddd'], category: 'web-backend', kind: 'concept' },
  { name: 'Hexagonal Architecture', category: 'web-backend', kind: 'concept' },
  { name: 'CQRS', category: 'web-backend', kind: 'concept' },
  { name: 'Event Sourcing', category: 'web-backend', kind: 'concept' },
  { name: 'API Gateway', category: 'web-backend', kind: 'concept' },
  { name: 'Service Mesh', category: 'web-backend', kind: 'concept' },

  { name: 'iOS', category: 'mobile', kind: 'platform' },
  { name: 'Android', category: 'mobile', kind: 'platform' },
  { name: 'React Native', category: 'mobile', kind: 'framework' },
  { name: 'Flutter', category: 'mobile', kind: 'framework' },
  { name: 'SwiftUI', category: 'mobile', kind: 'framework' },
  { name: 'UIKit', category: 'mobile', kind: 'framework' },
  { name: 'Jetpack Compose', category: 'mobile', kind: 'framework' },
  { name: 'Ionic', category: 'mobile', kind: 'framework' },
  { name: 'Capacitor', category: 'mobile', kind: 'framework' },
  { name: 'Expo', category: 'mobile', kind: 'platform' },
  { name: 'Core Data', category: 'mobile', kind: 'framework' },
  { name: 'Realm', category: 'mobile', kind: 'database' },
  { name: 'In-App Purchases', aliases: ['iap'], category: 'mobile', kind: 'concept' },
  { name: 'Push Notifications', category: 'mobile', kind: 'concept' },
  { name: 'App Store Connect', category: 'mobile', kind: 'tool' },
  { name: 'TestFlight', category: 'mobile', kind: 'tool' },

  { name: 'PostgreSQL', aliases: ['postgres'], category: 'databases', kind: 'database' },
  { name: 'MySQL', category: 'databases', kind: 'database' },
  { name: 'MariaDB', category: 'databases', kind: 'database' },
  { name: 'SQLite', category: 'databases', kind: 'database' },
  { name: 'Oracle Database', aliases: ['oracle db'], category: 'databases', kind: 'database' },
  { name: 'SQL Server', aliases: ['mssql', 'microsoft sql server'], category: 'databases', kind: 'database' },
  { name: 'MongoDB', category: 'databases', kind: 'database' },
  { name: 'DynamoDB', category: 'databases', kind: 'database' },
  { name: 'Cassandra', category: 'databases', kind: 'database' },
  { name: 'ScyllaDB', category: 'databases', kind: 'database' },
  { name: 'CockroachDB', category: 'databases', kind: 'database' },
  { name: 'Redis', category: 'databases', kind: 'database' },
  { name: 'Memcached', category: 'databases', kind: 'database' },
  { name: 'Elasticsearch', category: 'databases', kind: 'database' },
  { name: 'OpenSearch', category: 'databases', kind: 'database' },
  { name: 'Solr', category: 'databases', kind: 'database' },
  { name: 'Neo4j', category: 'databases', kind: 'database' },
  { name: 'ArangoDB', category: 'databases', kind: 'database' },
  { name: 'InfluxDB', category: 'databases', kind: 'database' },
  { name: 'TimescaleDB', category: 'databases', kind: 'database' },
  { name: 'ClickHouse', category: 'databases', kind: 'database' },
  { name: 'Snowflake', category: 'databases', kind: 'platform' },
  { name: 'BigQuery', category: 'databases', kind: 'platform' },
  { name: 'Redshift', category: 'databases', kind: 'platform' },
  { name: 'Databricks', category: 'databases', kind: 'platform' },
  { name: 'Cosmos DB', category: 'databases', kind: 'database' },
  { name: 'Firestore', category: 'databases', kind: 'database' },
  { name: 'Supabase', category: 'databases', kind: 'platform' },
  { name: 'Prisma', category: 'databases', kind: 'tool' },
  { name: 'Drizzle', category: 'databases', kind: 'tool' },
  { name: 'SQLAlchemy', category: 'databases', kind: 'tool' },
  { name: 'Sequelize', category: 'databases', kind: 'tool' },
  { name: 'TypeORM', category: 'databases', kind: 'tool' },
  { name: 'Hibernate', category: 'databases', kind: 'tool' },
  { name: 'Kafka', aliases: ['apache kafka'], category: 'databases', kind: 'platform' },
  { name: 'RabbitMQ', category: 'databases', kind: 'platform' },
  { name: 'NATS', category: 'databases', kind: 'platform' },
  { name: 'Pulsar', aliases: ['apache pulsar'], category: 'databases', kind: 'platform' },
  { name: 'ActiveMQ', category: 'databases', kind: 'platform' },

  { name: 'AWS', aliases: ['amazon web services'], category: 'cloud-devops', kind: 'platform' },
  { name: 'GCP', aliases: ['google cloud platform', 'google cloud'], category: 'cloud-devops', kind: 'platform' },
  { name: 'Azure', aliases: ['microsoft azure'], category: 'cloud-devops', kind: 'platform' },
  { name: 'Cloudflare', category: 'cloud-devops', kind: 'platform' },
  { name: 'Vercel', category: 'cloud-devops', kind: 'platform' },
  { name: 'Netlify', category: 'cloud-devops', kind: 'platform' },
  { name: 'Heroku', category: 'cloud-devops', kind: 'platform' },
  { name: 'DigitalOcean', category: 'cloud-devops', kind: 'platform' },
  { name: 'Linode', category: 'cloud-devops', kind: 'platform' },
  { name: 'EC2', category: 'cloud-devops', kind: 'platform' },
  { name: 'S3', category: 'cloud-devops', kind: 'platform' },
  { name: 'Lambda', aliases: ['aws lambda'], category: 'cloud-devops', kind: 'platform' },
  { name: 'CloudFront', category: 'cloud-devops', kind: 'platform' },
  { name: 'Route 53', category: 'cloud-devops', kind: 'platform' },
  { name: 'IAM', category: 'cloud-devops', kind: 'concept' },
  { name: 'VPC', category: 'cloud-devops', kind: 'concept' },
  { name: 'ECS', category: 'cloud-devops', kind: 'platform' },
  { name: 'EKS', category: 'cloud-devops', kind: 'platform' },
  { name: 'Fargate', category: 'cloud-devops', kind: 'platform' },
  { name: 'Step Functions', category: 'cloud-devops', kind: 'platform' },
  { name: 'SQS', category: 'cloud-devops', kind: 'platform' },
  { name: 'SNS', category: 'cloud-devops', kind: 'platform' },
  { name: 'Cloud Functions', aliases: ['gcp cloud functions'], category: 'cloud-devops', kind: 'platform' },
  { name: 'Cloud Run', category: 'cloud-devops', kind: 'platform' },
  { name: 'GKE', aliases: ['google kubernetes engine'], category: 'cloud-devops', kind: 'platform' },
  { name: 'Pub/Sub', category: 'cloud-devops', kind: 'platform' },
  { name: 'AKS', aliases: ['azure kubernetes service'], category: 'cloud-devops', kind: 'platform' },
  { name: 'Docker', category: 'cloud-devops', kind: 'tool' },
  { name: 'Kubernetes', aliases: ['k8s'], category: 'cloud-devops', kind: 'platform' },
  { name: 'Helm', category: 'cloud-devops', kind: 'tool' },
  { name: 'Terraform', category: 'cloud-devops', kind: 'tool' },
  { name: 'Pulumi', category: 'cloud-devops', kind: 'tool' },
  { name: 'Ansible', category: 'cloud-devops', kind: 'tool' },
  { name: 'Chef', category: 'cloud-devops', kind: 'tool' },
  { name: 'Puppet', category: 'cloud-devops', kind: 'tool' },
  { name: 'Jenkins', category: 'cloud-devops', kind: 'tool' },
  { name: 'CircleCI', category: 'cloud-devops', kind: 'tool' },
  { name: 'GitHub Actions', category: 'cloud-devops', kind: 'tool' },
  { name: 'GitLab CI', aliases: ['gitlab pipelines'], category: 'cloud-devops', kind: 'tool' },
  { name: 'Argo CD', aliases: ['argocd'], category: 'cloud-devops', kind: 'tool' },
  { name: 'Flux', category: 'cloud-devops', kind: 'tool' },
  { name: 'Spinnaker', category: 'cloud-devops', kind: 'tool' },
  { name: 'Prometheus', category: 'cloud-devops', kind: 'tool' },
  { name: 'Grafana', category: 'cloud-devops', kind: 'tool' },
  { name: 'Datadog', category: 'cloud-devops', kind: 'tool' },
  { name: 'New Relic', category: 'cloud-devops', kind: 'tool' },
  { name: 'Splunk', category: 'cloud-devops', kind: 'tool' },
  { name: 'Sentry', category: 'cloud-devops', kind: 'tool' },
  { name: 'PagerDuty', category: 'cloud-devops', kind: 'tool' },
  { name: 'Honeycomb', category: 'cloud-devops', kind: 'tool' },
  { name: 'OpenTelemetry', aliases: ['otel'], category: 'cloud-devops', kind: 'tool' },
  { name: 'Linux', category: 'cloud-devops', kind: 'platform' },
  { name: 'Nginx', category: 'cloud-devops', kind: 'tool' },
  { name: 'Apache HTTP Server', aliases: ['apache'], category: 'cloud-devops', kind: 'tool' },
  { name: 'HAProxy', category: 'cloud-devops', kind: 'tool' },
  { name: 'Envoy', category: 'cloud-devops', kind: 'tool' },
  { name: 'Istio', category: 'cloud-devops', kind: 'tool' },
  { name: 'Linkerd', category: 'cloud-devops', kind: 'tool' },
  { name: 'CI/CD', aliases: ['continuous integration', 'continuous delivery'], category: 'cloud-devops', kind: 'concept' },
  { name: 'GitOps', category: 'cloud-devops', kind: 'concept' },
  { name: 'Infrastructure as Code', aliases: ['iac'], category: 'cloud-devops', kind: 'concept' },
  { name: 'Site Reliability Engineering', aliases: ['sre'], category: 'cloud-devops', kind: 'concept' },
  { name: 'Observability', category: 'cloud-devops', kind: 'concept' },
  { name: 'Chaos Engineering', category: 'cloud-devops', kind: 'concept' },
  { name: 'Blue-Green Deployment', category: 'cloud-devops', kind: 'concept' },
  { name: 'Canary Deployment', category: 'cloud-devops', kind: 'concept' },
  { name: 'Git', category: 'cloud-devops', kind: 'tool' },
  { name: 'GitHub', category: 'cloud-devops', kind: 'platform' },
  { name: 'GitLab', category: 'cloud-devops', kind: 'platform' },
  { name: 'Bitbucket', category: 'cloud-devops', kind: 'platform' },

  { name: 'TensorFlow', category: 'data-ml', kind: 'library' },
  { name: 'PyTorch', category: 'data-ml', kind: 'library' },
  { name: 'Keras', category: 'data-ml', kind: 'library' },
  { name: 'scikit-learn', aliases: ['sklearn'], category: 'data-ml', kind: 'library' },
  { name: 'Pandas', category: 'data-ml', kind: 'library' },
  { name: 'NumPy', category: 'data-ml', kind: 'library' },
  { name: 'SciPy', category: 'data-ml', kind: 'library' },
  { name: 'Matplotlib', category: 'data-ml', kind: 'library' },
  { name: 'Seaborn', category: 'data-ml', kind: 'library' },
  { name: 'Plotly', category: 'data-ml', kind: 'library' },
  { name: 'Dask', category: 'data-ml', kind: 'library' },
  { name: 'Polars', category: 'data-ml', kind: 'library' },
  { name: 'Spark', aliases: ['apache spark', 'pyspark'], category: 'data-ml', kind: 'platform' },
  { name: 'Hadoop', category: 'data-ml', kind: 'platform' },
  { name: 'Hive', category: 'data-ml', kind: 'platform' },
  { name: 'Presto', category: 'data-ml', kind: 'platform' },
  { name: 'Trino', category: 'data-ml', kind: 'platform' },
  { name: 'Airflow', aliases: ['apache airflow'], category: 'data-ml', kind: 'tool' },
  { name: 'Prefect', category: 'data-ml', kind: 'tool' },
  { name: 'Dagster', category: 'data-ml', kind: 'tool' },
  { name: 'dbt', category: 'data-ml', kind: 'tool' },
  { name: 'Great Expectations', category: 'data-ml', kind: 'tool' },
  { name: 'MLflow', category: 'data-ml', kind: 'tool' },
  { name: 'Weights & Biases', aliases: ['wandb'], category: 'data-ml', kind: 'tool' },
  { name: 'Kubeflow', category: 'data-ml', kind: 'platform' },
  { name: 'Ray', category: 'data-ml', kind: 'platform' },
  { name: 'Hugging Face', aliases: ['huggingface', 'transformers'], category: 'data-ml', kind: 'platform' },
  { name: 'LangChain', category: 'data-ml', kind: 'library' },
  { name: 'LlamaIndex', category: 'data-ml', kind: 'library' },
  { name: 'OpenAI', aliases: ['openai api', 'gpt-4', 'gpt-4o'], category: 'data-ml', kind: 'platform' },
  { name: 'Anthropic', aliases: ['claude'], category: 'data-ml', kind: 'platform' },
  { name: 'Large Language Models', aliases: ['llm', 'llms'], category: 'data-ml', kind: 'concept' },
  { name: 'Retrieval-Augmented Generation', aliases: ['rag'], category: 'data-ml', kind: 'concept' },
  { name: 'Vector Databases', aliases: ['vector db', 'vector search'], category: 'data-ml', kind: 'concept' },
  { name: 'Pinecone', category: 'data-ml', kind: 'database' },
  { name: 'Weaviate', category: 'data-ml', kind: 'database' },
  { name: 'Chroma', category: 'data-ml', kind: 'database' },
  { name: 'Qdrant', category: 'data-ml', kind: 'database' },
  { name: 'Milvus', category: 'data-ml', kind: 'database' },
  { name: 'pgvector', category: 'data-ml', kind: 'library' },
  { name: 'Stable Diffusion', category: 'data-ml', kind: 'concept' },
  { name: 'Machine Learning', aliases: ['ml'], category: 'data-ml', kind: 'concept' },
  { name: 'Deep Learning', category: 'data-ml', kind: 'concept' },
  { name: 'Natural Language Processing', aliases: ['nlp'], category: 'data-ml', kind: 'concept' },
  { name: 'Computer Vision', aliases: ['cv'], category: 'data-ml', kind: 'concept' },
  { name: 'Reinforcement Learning', aliases: ['rl'], category: 'data-ml', kind: 'concept' },
  { name: 'Time Series Analysis', category: 'data-ml', kind: 'concept' },
  { name: 'Statistical Modeling', category: 'data-ml', kind: 'concept' },
  { name: 'A/B Testing', aliases: ['ab testing', 'experimentation'], category: 'data-ml', kind: 'concept' },
  { name: 'Data Engineering', category: 'data-ml', kind: 'concept' },
  { name: 'Data Modeling', category: 'data-ml', kind: 'concept' },
  { name: 'ETL', aliases: ['elt'], category: 'data-ml', kind: 'concept' },
  { name: 'Data Warehousing', category: 'data-ml', kind: 'concept' },
  { name: 'Data Lakes', category: 'data-ml', kind: 'concept' },
  { name: 'Feature Engineering', category: 'data-ml', kind: 'concept' },
  { name: 'MLOps', category: 'data-ml', kind: 'concept' },
  { name: 'Tableau', category: 'data-ml', kind: 'tool' },
  { name: 'Power BI', aliases: ['powerbi'], category: 'data-ml', kind: 'tool' },
  { name: 'Looker', category: 'data-ml', kind: 'tool' },
  { name: 'Mode', aliases: ['mode analytics'], category: 'data-ml', kind: 'tool' },
  { name: 'Metabase', category: 'data-ml', kind: 'tool' },

  { name: 'Figma', category: 'design-ux', kind: 'tool' },
  { name: 'Sketch', category: 'design-ux', kind: 'tool' },
  { name: 'Adobe XD', category: 'design-ux', kind: 'tool' },
  { name: 'Photoshop', aliases: ['adobe photoshop'], category: 'design-ux', kind: 'tool' },
  { name: 'Illustrator', aliases: ['adobe illustrator'], category: 'design-ux', kind: 'tool' },
  { name: 'InDesign', aliases: ['adobe indesign'], category: 'design-ux', kind: 'tool' },
  { name: 'After Effects', aliases: ['adobe after effects'], category: 'design-ux', kind: 'tool' },
  { name: 'Premiere Pro', aliases: ['adobe premiere'], category: 'design-ux', kind: 'tool' },
  { name: 'Affinity Designer', category: 'design-ux', kind: 'tool' },
  { name: 'Affinity Photo', category: 'design-ux', kind: 'tool' },
  { name: 'Framer', category: 'design-ux', kind: 'tool' },
  { name: 'Webflow', category: 'design-ux', kind: 'tool' },
  { name: 'Principle', category: 'design-ux', kind: 'tool' },
  { name: 'Whimsical', category: 'design-ux', kind: 'tool' },
  { name: 'Miro', category: 'design-ux', kind: 'tool' },
  { name: 'Mural', category: 'design-ux', kind: 'tool' },
  { name: 'FigJam', category: 'design-ux', kind: 'tool' },
  { name: 'UX Design', aliases: ['user experience design'], category: 'design-ux', kind: 'concept' },
  { name: 'UI Design', aliases: ['user interface design'], category: 'design-ux', kind: 'concept' },
  { name: 'User Research', category: 'design-ux', kind: 'concept' },
  { name: 'Information Architecture', aliases: ['ia'], category: 'design-ux', kind: 'concept' },
  { name: 'Wireframing', category: 'design-ux', kind: 'concept' },
  { name: 'Prototyping', category: 'design-ux', kind: 'concept' },
  { name: 'Design Systems', category: 'design-ux', kind: 'concept' },
  { name: 'Visual Design', category: 'design-ux', kind: 'concept' },
  { name: 'Interaction Design', aliases: ['ixd'], category: 'design-ux', kind: 'concept' },
  { name: 'Motion Design', category: 'design-ux', kind: 'concept' },
  { name: 'Typography', category: 'design-ux', kind: 'concept' },
  { name: 'Usability Testing', category: 'design-ux', kind: 'concept' },
  { name: 'Heuristic Evaluation', category: 'design-ux', kind: 'concept' },
  { name: 'Journey Mapping', category: 'design-ux', kind: 'concept' },
  { name: 'Service Design', category: 'design-ux', kind: 'concept' },
  { name: 'Design Thinking', category: 'design-ux', kind: 'methodology' },

  { name: 'SEO', aliases: ['search engine optimization'], category: 'marketing', kind: 'concept' },
  { name: 'SEM', aliases: ['search engine marketing'], category: 'marketing', kind: 'concept' },
  { name: 'PPC', aliases: ['pay-per-click'], category: 'marketing', kind: 'concept' },
  { name: 'Google Ads', aliases: ['adwords'], category: 'marketing', kind: 'tool' },
  { name: 'Facebook Ads', aliases: ['meta ads'], category: 'marketing', kind: 'tool' },
  { name: 'LinkedIn Ads', category: 'marketing', kind: 'tool' },
  { name: 'TikTok Ads', category: 'marketing', kind: 'tool' },
  { name: 'Google Analytics', aliases: ['ga4', 'ga'], category: 'marketing', kind: 'tool' },
  { name: 'Mixpanel', category: 'marketing', kind: 'tool' },
  { name: 'Amplitude', category: 'marketing', kind: 'tool' },
  { name: 'Heap', category: 'marketing', kind: 'tool' },
  { name: 'Segment', category: 'marketing', kind: 'tool' },
  { name: 'Adobe Analytics', category: 'marketing', kind: 'tool' },
  { name: 'HubSpot', category: 'marketing', kind: 'platform' },
  { name: 'Marketo', category: 'marketing', kind: 'platform' },
  { name: 'Mailchimp', category: 'marketing', kind: 'tool' },
  { name: 'SendGrid', category: 'marketing', kind: 'tool' },
  { name: 'Klaviyo', category: 'marketing', kind: 'platform' },
  { name: 'Salesforce Marketing Cloud', category: 'marketing', kind: 'platform' },
  { name: 'Pardot', category: 'marketing', kind: 'platform' },
  { name: 'Demand Generation', aliases: ['demand gen'], category: 'marketing', kind: 'concept' },
  { name: 'Lead Generation', aliases: ['lead gen'], category: 'marketing', kind: 'concept' },
  { name: 'Content Marketing', category: 'marketing', kind: 'concept' },
  { name: 'Email Marketing', category: 'marketing', kind: 'concept' },
  { name: 'Social Media Marketing', category: 'marketing', kind: 'concept' },
  { name: 'Influencer Marketing', category: 'marketing', kind: 'concept' },
  { name: 'Affiliate Marketing', category: 'marketing', kind: 'concept' },
  { name: 'Brand Marketing', aliases: ['brand strategy'], category: 'marketing', kind: 'concept' },
  { name: 'Product Marketing', aliases: ['pmm'], category: 'marketing', kind: 'concept' },
  { name: 'Growth Marketing', category: 'marketing', kind: 'concept' },
  { name: 'Account-Based Marketing', aliases: ['abm'], category: 'marketing', kind: 'concept' },
  { name: 'Conversion Rate Optimization', aliases: ['cro'], category: 'marketing', kind: 'concept' },
  { name: 'Marketing Automation', category: 'marketing', kind: 'concept' },
  { name: 'Copywriting', category: 'marketing', kind: 'concept' },
  { name: 'Positioning', category: 'marketing', kind: 'concept' },
  { name: 'Messaging', category: 'marketing', kind: 'concept' },
  { name: 'Go-to-Market', aliases: ['gtm'], category: 'marketing', kind: 'concept' },
  { name: 'Keyword Research', category: 'marketing', kind: 'concept' },
  { name: 'Link Building', category: 'marketing', kind: 'concept' },
  { name: 'Technical SEO', category: 'marketing', kind: 'concept' },

  { name: 'Salesforce', aliases: ['sfdc'], category: 'sales', kind: 'platform' },
  { name: 'Outreach', category: 'sales', kind: 'tool' },
  { name: 'SalesLoft', category: 'sales', kind: 'tool' },
  { name: 'Gong', category: 'sales', kind: 'tool' },
  { name: 'Chorus', category: 'sales', kind: 'tool' },
  { name: 'ZoomInfo', category: 'sales', kind: 'tool' },
  { name: 'Apollo.io', aliases: ['apollo'], category: 'sales', kind: 'tool' },
  { name: 'Cold Calling', category: 'sales', kind: 'concept' },
  { name: 'Cold Email', aliases: ['cold outreach'], category: 'sales', kind: 'concept' },
  { name: 'Discovery Calls', aliases: ['discovery'], category: 'sales', kind: 'concept' },
  { name: 'BANT', category: 'sales', kind: 'methodology' },
  { name: 'MEDDIC', category: 'sales', kind: 'methodology' },
  { name: 'MEDDPICC', category: 'sales', kind: 'methodology' },
  { name: 'Sandler', category: 'sales', kind: 'methodology' },
  { name: 'Challenger Sale', category: 'sales', kind: 'methodology' },
  { name: 'Pipeline Management', category: 'sales', kind: 'concept' },
  { name: 'Forecasting', category: 'sales', kind: 'concept' },
  { name: 'Quota Attainment', category: 'sales', kind: 'concept' },
  { name: 'Enterprise Sales', category: 'sales', kind: 'concept' },
  { name: 'Inside Sales', category: 'sales', kind: 'concept' },
  { name: 'SDR', aliases: ['sales development representative'], category: 'sales', kind: 'concept' },
  { name: 'BDR', aliases: ['business development representative'], category: 'sales', kind: 'concept' },
  { name: 'Account Executive', aliases: ['ae'], category: 'sales', kind: 'concept' },
  { name: 'Customer Success', aliases: ['csm'], category: 'sales', kind: 'concept' },
  { name: 'Channel Sales', category: 'sales', kind: 'concept' },
  { name: 'Partnerships', category: 'sales', kind: 'concept' },

  { name: 'Financial Modeling', category: 'finance', kind: 'concept' },
  { name: 'Excel', aliases: ['microsoft excel'], category: 'finance', kind: 'tool' },
  { name: 'Bloomberg Terminal', aliases: ['bloomberg'], category: 'finance', kind: 'tool' },
  { name: 'FactSet', category: 'finance', kind: 'tool' },
  { name: 'Capital IQ', aliases: ['capiq'], category: 'finance', kind: 'tool' },
  { name: 'GAAP', category: 'finance', kind: 'concept' },
  { name: 'IFRS', category: 'finance', kind: 'concept' },
  { name: 'SOX', aliases: ['sarbanes-oxley'], category: 'finance', kind: 'concept' },
  { name: 'M&A', aliases: ['mergers and acquisitions'], category: 'finance', kind: 'concept' },
  { name: 'IPO', category: 'finance', kind: 'concept' },
  { name: 'LBO', aliases: ['leveraged buyout'], category: 'finance', kind: 'concept' },
  { name: 'DCF', aliases: ['discounted cash flow'], category: 'finance', kind: 'concept' },
  { name: 'Valuation', category: 'finance', kind: 'concept' },
  { name: 'Equity Research', category: 'finance', kind: 'concept' },
  { name: 'Investment Banking', category: 'finance', kind: 'concept' },
  { name: 'Private Equity', aliases: ['pe'], category: 'finance', kind: 'concept' },
  { name: 'Venture Capital', aliases: ['vc'], category: 'finance', kind: 'concept' },
  { name: 'Hedge Fund', category: 'finance', kind: 'concept' },
  { name: 'Treasury Management', category: 'finance', kind: 'concept' },
  { name: 'Risk Management', category: 'finance', kind: 'concept' },
  { name: 'Compliance', category: 'finance', kind: 'concept' },
  { name: 'AML', aliases: ['anti-money laundering'], category: 'finance', kind: 'concept' },
  { name: 'KYC', aliases: ['know your customer'], category: 'finance', kind: 'concept' },
  { name: 'FP&A', aliases: ['financial planning and analysis'], category: 'finance', kind: 'concept' },
  { name: 'Budgeting', category: 'finance', kind: 'concept' },
  { name: 'Variance Analysis', category: 'finance', kind: 'concept' },
  { name: 'Reconciliation', category: 'finance', kind: 'concept' },
  { name: 'General Ledger', aliases: ['gl'], category: 'finance', kind: 'concept' },
  { name: 'Accounts Receivable', aliases: ['ar'], category: 'finance', kind: 'concept' },
  { name: 'Accounts Payable', aliases: ['ap'], category: 'finance', kind: 'concept' },
  { name: 'QuickBooks', category: 'finance', kind: 'tool' },
  { name: 'NetSuite', category: 'finance', kind: 'platform' },
  { name: 'SAP', category: 'finance', kind: 'platform' },
  { name: 'Workday', category: 'finance', kind: 'platform' },
  { name: 'Hyperion', category: 'finance', kind: 'platform' },

  { name: 'Agile', category: 'business-ops', kind: 'methodology' },
  { name: 'Scrum', category: 'business-ops', kind: 'methodology' },
  { name: 'Kanban', category: 'business-ops', kind: 'methodology' },
  { name: 'SAFe', aliases: ['scaled agile framework'], category: 'business-ops', kind: 'methodology' },
  { name: 'Waterfall', category: 'business-ops', kind: 'methodology' },
  { name: 'PMP', aliases: ['project management professional'], category: 'business-ops', kind: 'certification' },
  { name: 'PRINCE2', category: 'business-ops', kind: 'certification' },
  { name: 'Six Sigma', category: 'business-ops', kind: 'methodology' },
  { name: 'Lean', category: 'business-ops', kind: 'methodology' },
  { name: 'Lean Six Sigma', category: 'business-ops', kind: 'methodology' },
  { name: 'Continuous Improvement', category: 'business-ops', kind: 'concept' },
  { name: 'Change Management', category: 'business-ops', kind: 'concept' },
  { name: 'Stakeholder Management', category: 'business-ops', kind: 'concept' },
  { name: 'Vendor Management', category: 'business-ops', kind: 'concept' },
  { name: 'Procurement', category: 'business-ops', kind: 'concept' },
  { name: 'Supply Chain Management', aliases: ['scm'], category: 'business-ops', kind: 'concept' },
  { name: 'Logistics', category: 'business-ops', kind: 'concept' },
  { name: 'Inventory Management', category: 'business-ops', kind: 'concept' },
  { name: 'Strategic Planning', category: 'business-ops', kind: 'concept' },
  { name: 'Business Development', aliases: ['biz dev', 'bd'], category: 'business-ops', kind: 'concept' },
  { name: 'OKRs', aliases: ['objectives and key results'], category: 'business-ops', kind: 'methodology' },
  { name: 'KPIs', aliases: ['key performance indicators'], category: 'business-ops', kind: 'concept' },
  { name: 'Risk Assessment', category: 'business-ops', kind: 'concept' },
  { name: 'Jira', category: 'business-ops', kind: 'tool' },
  { name: 'Confluence', category: 'business-ops', kind: 'tool' },
  { name: 'Asana', category: 'business-ops', kind: 'tool' },
  { name: 'Trello', category: 'business-ops', kind: 'tool' },
  { name: 'Notion', category: 'business-ops', kind: 'tool' },
  { name: 'Monday.com', category: 'business-ops', kind: 'tool' },
  { name: 'Slack', category: 'business-ops', kind: 'tool' },
  { name: 'Microsoft Teams', category: 'business-ops', kind: 'tool' },
  { name: 'Microsoft Office', aliases: ['ms office', 'office 365'], category: 'business-ops', kind: 'tool' },
  { name: 'Google Workspace', aliases: ['g suite'], category: 'business-ops', kind: 'tool' },

  { name: 'Leadership', category: 'leadership-soft', kind: 'soft' },
  { name: 'Team Management', category: 'leadership-soft', kind: 'soft' },
  { name: 'People Management', category: 'leadership-soft', kind: 'soft' },
  { name: 'Mentoring', category: 'leadership-soft', kind: 'soft' },
  { name: 'Coaching', category: 'leadership-soft', kind: 'soft' },
  { name: 'Cross-functional Collaboration', aliases: ['cross-functional'], category: 'leadership-soft', kind: 'soft' },
  { name: 'Communication', category: 'leadership-soft', kind: 'soft' },
  { name: 'Public Speaking', category: 'leadership-soft', kind: 'soft' },
  { name: 'Presentation Skills', category: 'leadership-soft', kind: 'soft' },
  { name: 'Stakeholder Communication', category: 'leadership-soft', kind: 'soft' },
  { name: 'Conflict Resolution', category: 'leadership-soft', kind: 'soft' },
  { name: 'Negotiation', category: 'leadership-soft', kind: 'soft' },
  { name: 'Decision Making', category: 'leadership-soft', kind: 'soft' },
  { name: 'Problem Solving', category: 'leadership-soft', kind: 'soft' },
  { name: 'Critical Thinking', category: 'leadership-soft', kind: 'soft' },
  { name: 'Strategic Thinking', category: 'leadership-soft', kind: 'soft' },
  { name: 'Analytical Skills', category: 'leadership-soft', kind: 'soft' },
  { name: 'Time Management', category: 'leadership-soft', kind: 'soft' },
  { name: 'Project Management', aliases: ['pm'], category: 'leadership-soft', kind: 'soft' },
  { name: 'Hiring', category: 'leadership-soft', kind: 'soft' },
  { name: 'Performance Management', category: 'leadership-soft', kind: 'soft' },
  { name: 'Career Development', category: 'leadership-soft', kind: 'soft' },
  { name: 'Diversity & Inclusion', aliases: ['dei', 'd&i'], category: 'leadership-soft', kind: 'soft' },
  { name: 'Empathy', category: 'leadership-soft', kind: 'soft' },
  { name: 'Adaptability', category: 'leadership-soft', kind: 'soft' },
  { name: 'Resilience', category: 'leadership-soft', kind: 'soft' },
  { name: 'Self-Direction', category: 'leadership-soft', kind: 'soft' },
  { name: 'Emotional Intelligence', aliases: ['eq'], category: 'leadership-soft', kind: 'soft' },

  { name: 'EHR', aliases: ['electronic health records'], category: 'healthcare', kind: 'concept' },
  { name: 'EMR', aliases: ['electronic medical records'], category: 'healthcare', kind: 'concept' },
  { name: 'Epic', category: 'healthcare', kind: 'platform' },
  { name: 'Cerner', category: 'healthcare', kind: 'platform' },
  { name: 'HIPAA', category: 'healthcare', kind: 'certification' },
  { name: 'FHIR', category: 'healthcare', kind: 'concept' },
  { name: 'HL7', category: 'healthcare', kind: 'concept' },
  { name: 'Patient Care', category: 'healthcare', kind: 'concept' },
  { name: 'Telehealth', category: 'healthcare', kind: 'concept' },
  { name: 'Clinical Documentation', category: 'healthcare', kind: 'concept' },
  { name: 'Medical Coding', category: 'healthcare', kind: 'concept' },
  { name: 'ICD-10', category: 'healthcare', kind: 'concept' },
  { name: 'CPT', category: 'healthcare', kind: 'concept' },
  { name: 'Population Health', category: 'healthcare', kind: 'concept' },
  { name: 'Value-Based Care', category: 'healthcare', kind: 'concept' },
  { name: 'Clinical Trials', category: 'healthcare', kind: 'concept' },

  { name: 'Cybersecurity', aliases: ['cyber security'], category: 'security', kind: 'concept' },
  { name: 'Information Security', aliases: ['infosec'], category: 'security', kind: 'concept' },
  { name: 'Application Security', aliases: ['appsec'], category: 'security', kind: 'concept' },
  { name: 'Network Security', category: 'security', kind: 'concept' },
  { name: 'Cloud Security', category: 'security', kind: 'concept' },
  { name: 'DevSecOps', category: 'security', kind: 'concept' },
  { name: 'Penetration Testing', aliases: ['pen testing', 'pentest'], category: 'security', kind: 'concept' },
  { name: 'Vulnerability Assessment', category: 'security', kind: 'concept' },
  { name: 'Threat Modeling', category: 'security', kind: 'concept' },
  { name: 'Red Team', category: 'security', kind: 'concept' },
  { name: 'Blue Team', category: 'security', kind: 'concept' },
  { name: 'SOC', aliases: ['security operations center'], category: 'security', kind: 'concept' },
  { name: 'SIEM', category: 'security', kind: 'concept' },
  { name: 'Incident Response', aliases: ['ir'], category: 'security', kind: 'concept' },
  { name: 'Threat Hunting', category: 'security', kind: 'concept' },
  { name: 'Threat Intelligence', category: 'security', kind: 'concept' },
  { name: 'SOC 2', category: 'security', kind: 'certification' },
  { name: 'ISO 27001', category: 'security', kind: 'certification' },
  { name: 'PCI DSS', category: 'security', kind: 'certification' },
  { name: 'GDPR', category: 'security', kind: 'certification' },
  { name: 'CCPA', category: 'security', kind: 'certification' },
  { name: 'NIST', category: 'security', kind: 'certification' },
  { name: 'OWASP', category: 'security', kind: 'concept' },
  { name: 'CISSP', category: 'security', kind: 'certification' },
  { name: 'CISM', category: 'security', kind: 'certification' },
  { name: 'CEH', aliases: ['certified ethical hacker'], category: 'security', kind: 'certification' },
  { name: 'OSCP', category: 'security', kind: 'certification' },
  { name: 'Burp Suite', category: 'security', kind: 'tool' },
  { name: 'Wireshark', category: 'security', kind: 'tool' },
  { name: 'Metasploit', category: 'security', kind: 'tool' },
  { name: 'Nmap', category: 'security', kind: 'tool' },

  { name: 'Product Management', aliases: ['product mgmt'], category: 'product-mgmt', kind: 'concept' },
  { name: 'Product Strategy', category: 'product-mgmt', kind: 'concept' },
  { name: 'Product Roadmap', aliases: ['roadmapping'], category: 'product-mgmt', kind: 'concept' },
  { name: 'Product Discovery', category: 'product-mgmt', kind: 'concept' },
  { name: 'Product-Market Fit', aliases: ['pmf'], category: 'product-mgmt', kind: 'concept' },
  { name: 'Customer Interviews', category: 'product-mgmt', kind: 'concept' },
  { name: 'Jobs to Be Done', aliases: ['jtbd'], category: 'product-mgmt', kind: 'methodology' },
  { name: 'Experimentation', category: 'product-mgmt', kind: 'concept' },
  { name: 'Feature Flags', category: 'product-mgmt', kind: 'concept' },
  { name: 'Prioritization', category: 'product-mgmt', kind: 'concept' },
  { name: 'RICE', category: 'product-mgmt', kind: 'methodology' },
  { name: 'Backlog Management', category: 'product-mgmt', kind: 'concept' },
  { name: 'Product Analytics', category: 'product-mgmt', kind: 'concept' },
  { name: 'Funnel Analysis', aliases: ['funnels'], category: 'product-mgmt', kind: 'concept' },
  { name: 'Cohort Analysis', category: 'product-mgmt', kind: 'concept' },
  { name: 'Retention', category: 'product-mgmt', kind: 'concept' },
  { name: 'Activation', category: 'product-mgmt', kind: 'concept' },
  { name: 'NPS', aliases: ['net promoter score'], category: 'product-mgmt', kind: 'concept' },
  { name: 'PLG', aliases: ['product-led growth'], category: 'product-mgmt', kind: 'concept' },

  { name: 'Test Automation', category: 'qa-testing', kind: 'concept' },
  { name: 'Selenium', category: 'qa-testing', kind: 'tool' },
  { name: 'Cypress', category: 'qa-testing', kind: 'tool' },
  { name: 'Playwright', category: 'qa-testing', kind: 'tool' },
  { name: 'Puppeteer', category: 'qa-testing', kind: 'tool' },
  { name: 'WebdriverIO', category: 'qa-testing', kind: 'tool' },
  { name: 'Appium', category: 'qa-testing', kind: 'tool' },
  { name: 'Jest', category: 'qa-testing', kind: 'tool' },
  { name: 'Vitest', category: 'qa-testing', kind: 'tool' },
  { name: 'Mocha', category: 'qa-testing', kind: 'tool' },
  { name: 'Pytest', category: 'qa-testing', kind: 'tool' },
  { name: 'JUnit', category: 'qa-testing', kind: 'tool' },
  { name: 'RSpec', category: 'qa-testing', kind: 'tool' },
  { name: 'Testing Library', aliases: ['react testing library'], category: 'qa-testing', kind: 'tool' },
  { name: 'Postman', category: 'qa-testing', kind: 'tool' },
  { name: 'k6', category: 'qa-testing', kind: 'tool' },
  { name: 'JMeter', category: 'qa-testing', kind: 'tool' },
  { name: 'Locust', category: 'qa-testing', kind: 'tool' },
  { name: 'Gatling', category: 'qa-testing', kind: 'tool' },
  { name: 'Unit Testing', category: 'qa-testing', kind: 'concept' },
  { name: 'Integration Testing', category: 'qa-testing', kind: 'concept' },
  { name: 'End-to-End Testing', aliases: ['e2e testing'], category: 'qa-testing', kind: 'concept' },
  { name: 'Performance Testing', category: 'qa-testing', kind: 'concept' },
  { name: 'Load Testing', category: 'qa-testing', kind: 'concept' },
  { name: 'Test-Driven Development', aliases: ['tdd'], category: 'qa-testing', kind: 'methodology' },
  { name: 'Behavior-Driven Development', aliases: ['bdd'], category: 'qa-testing', kind: 'methodology' },
];
