export type ResumeFontFamily =
  | 'Inter'
  | 'Source Sans 3'
  | 'Lato'
  | 'Open Sans'
  | 'Manrope'
  | 'Work Sans'
  | 'Nunito Sans'
  | 'Source Serif 4'
  | 'EB Garamond'
  | 'Lora'
  | 'Merriweather'
  | 'Newsreader'
  | 'Spectral'
  | 'PT Serif'
  | 'JetBrains Mono';
